name: Wait for netlify deploy
on: 
  check_suite:
    conclusion: success

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo hello world! $TARGET_URL
        env:
          TARGET_URL: '${{ github.event.deployment_status.target_url }}'